routes:
  "/new_user":
    post:
      exchange: "amq.topic"
      routingKey: "guardian.request.newuser"
      roles:
        - "user"
        - "admin"
      inputMapping:
        username: "body.username"
        password: "body.password"
        roles: "body.roles"
  "/auth":
    post:
      exchange: "amq.topic"
      routingKey: "guardian.request.auth"
      inputMapping:
        username: "body.username"
        password: "body.password"
