routes:
  "/new_user":
    post:
      exchange: "amq.topic"
      routingKey: "guardian.request.newuser"
      rpc: true
      roles:
        - "user"
        - "admin"
      timeoutMs: 3000
      timeoutStatusCode: 504 
      inputMapping:
        username: "body.username"
        password: "body.password"
        roles: "body.roles"
  "/auth/:username":
    post:
      exchange: "amq.topic"
      routingKey: "guardian.request.auth"
      rpc: true
      timeoutMs: 3000
      timeoutStatusCode: 504 
      inputMapping:
        headers:
          x-username: "params.username"
        username: "params.username"
        password: "body.password"
