version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  cottontail:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AMQPURL=amqp://rabbitmq
