version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 5

  cottontail:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AMQP_URL=amqp://rabbitmq
    restart: always
    volumes:
      - ${PWD}/config.yml:/app/config.yml
