streams:

routes:
  "/test_stream":
    sse:
      exchange: "amq.topic"
      routingKey: "sample.stream"
      roles:
        - "user"
        - "admin"
  "/test_rpc":
    get:
      exchange: "amq.topic"
      routingKey: "guardian.request.newuser"
      rpc: true
      roles:
        - "user"
        - "admin"
      timeoutMs: 3000
      timeoutStatusCode: 504 
      inputMapping:
        username: "body.username"
        password: "body.password"
        roles: "body.roles"
  "/test_non_rpc":
    get:
      exchange: "amq.topic"
      routingKey: "guardian.request.newuser"
      rpc: false
      roles:
        - "user"
        - "admin"
      timeoutMs: 3000
      timeoutStatusCode: 504 
      inputMapping:
        username: "body.username"
        password: "body.password"
        roles: "body.roles"